config/routes.rb
Layouter::Application.routes.draw do
  resources :environmental_decision_parameters

  resources :market_demographics

  resources :mentality_values

  resources :mentality_rankings

  resources :mentalities

  resources :mentality_parameters

  resources :factory_vendors

  resources :plugin_samples

  resources :jquery_themes

  resources :font_themes

  resources :icon_themes

  resources :temps

  resources :pages

  resources :page_layouts

  resources :layout_themes

  resources :color_themes

  # get "welcome/index"
  match '/jquery_sample' => 'color_themes#jquery_sample'
  match '/icon_sample' => 'color_themes#icon_sample'
  match '/check_theme' => 'page_layouts#check_theme'


  resources :brands

  resources :player_round_factories

  resources :round_media_plans

  resources :player_round_loans

  resources :player_round_investments

  resources :player_round_expenses

  resources :default_player_data

  resources :players

  resources :player_financials

  resources :imports

  resources :games

  resources :student_group_users

  resources :round_loans

  resources :loan_types

  resources :investment_types

  resources :round_expenses

  resources :employees

  resources :employee_categories

  resources :constants

  resources :round_investments

  resources :media_plan_details

  resources :media_plans

  resources :impacts

  resources :units

  resources :expense_types

  resources :hrincentives

  resources :simulation_decision_parameters

  resources :simulation_markets

  resources :simulation_factories

  resources :student_groups

  resources :facilitator_groups

  resources :product_parameters

  resources :raw_materials

  resources :products

  resources :mathematical_model_variable_values

  resources :available_decision_parameters

  resources :mathematical_model_constant_values

  resources :mathematical_model_variables

  resources :mathematical_model_constants

  resources :round_environmental_parameters

  resources :expense_options

  resources :expenses

  resources :case_studies

  resources :player_investments

  resources :investments

  resources :player_loans

  resources :loans

  resources :media

  resources :consumer_brand_selection_parameters

  resources :brand_selection_parameters

  resources :consumer_media_preferences

  resources :consumer_categories

  resources :consumers

  resources :vendors

  resources :dealer_categories

  resources :dealer_push_indices

  resources :dealers

  resources :market_consumer_categories

  resources :market_distances

  resources :factories

  resources :markets

  resources :rounds

  resources :simulations

  resources :mathematical_model_inputs

  resources :mathematical_models

  resources :decision_parameters

  resources :environmental_parameters

  resources :facilitators

  resources :clients

  devise_for :users do
    get '/users/sign_out'=>'devise/sessions#destroy'
  end

  root :to=>'welcome#landing_page'

  match 'home_page'=>'welcome#home_page'

  match "define_constant_value"=>'decision_parameters#define_constant_value'
  match "set_constant_value"=>'decision_parameters#set_constant_value'
  match "define_variable_values"=>'decision_parameters#define_variable_values'
  match "set_variable_values"=>'decision_parameters#set_variable_values'
  match 'details'=>'decision_parameters#view_details'
  match 'view_parameters'=>'products#view_parameters'
  match 'view_expenses'=>'expenses#view_expenses'
  match 'view_distances'=>'markets#view_distances'
  match 'initiate_game'=>'games#initiate_game'
  match "get_student_group"=>'simulations#get_student_group'
  match "set_student_group"=>'simulations#set_student_group'
  match 'initiate_simulation'=>'simulations#initiate_simulation'
  match "register_as_expense"=>'media_plans#register_as_expense'
  match 'landing_page'=>'welcome#landing_page'
  match 'populate_rate_of_interest'=>'rounds#populate_rate_of_interest'
  match 'populate_depreciation'=>'rounds#populate_depreciation'
  match 'set_rate_of_interest'=>'rounds#set_rate_of_interest'
  match 'set_depreciation'=>'rounds#set_depreciation'
  match 'finalize_media_plan'=>'media_plans#finalize_media_plan'
  match 'select_initiate_simulation'=>'simulations#select_initiate_simulation'
  match 'view_tabular_market_distance'=>'market_distances#view_tabular_distances'
  match 'initiate_round_calculation'=>'simulations#initiate_round_calculation'
  match 'view_map'=>'markets#view_maps'
  match 'set_location'=>'markets#set_location'
  match 'update_market_distance'=>'market_distances#update_distances'
  match 'participation_management'=>'welcome#participation_management'
  match 'set_participation'=>'welcome#set_participation'
  match 'remove_student/:student_group_user_id', :to=>'welcome#remove_student'
  match 'set_simulation'=>'welcome#set_simulation'
  match 'remove_student_from_list/:user_id'=>'welcome#remove_student_from_list'
  match 'remove_media_plan_detail'=>'media_plans#remove_media_plan_detail'
  match 'register_as_expense'=>'media_plans#register_as_expense'


end

app/controllers/round_expenses_controller.rb
class RoundExpensesController < ApplicationController
  # GET /round_expenses
  # GET /round_expenses.json

  def index
    @round_expenses = RoundExpense.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @round_expenses }
    end
  end

  # GET /round_expenses/1
  # GET /round_expenses/1.json
  def show
    @round_expense = RoundExpense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @round_expense }
    end
  end

  # GET /round_expenses/new
  # GET /round_expenses/new.json
  def new
    @expense_types=ExpenseType.all
    @round=Round.find(params[:round_id])
    @round_expense = RoundExpense.new
    @expenses=Expense.all
    @round_expenses=Array.new(Expense.all.count) { RoundExpense.new }


    @included_expenses=@round.round_expenses
    @included_expenses_ids=Array.new
    @included_expenses.each do |expense|
      @included_expenses_ids << expense.expense_id

    end


    #this is the array we need to display in drop down
    @expense_list=Expense.all.collect { |expense|
      if @included_expenses_ids.include?(expense.id)==false then
        [expense.name, expense.id]
      end }.compact


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @round_expense }
    end
  end

  # GET /round_expenses/1/edit
  def edit
    @round_expense = RoundExpense.find(params[:id])
  end

  # POST /round_expenses
  # POST /round_expenses.json
  def create

    #@round_expense = RoundExpense.new(params[:round_expense])
    @round_expenses = params[:round_expenses].values.collect { |round_expense| RoundExpense.new(round_expense) }
    @round_expenses.each do |round_expense|
      if round_expense.summary!="Summary about expense" and round_expense.summary.strip.length>0
        round_expense.save!

      end
    end


    respond_to do |format|
      if @round_expenses.all?(&:valid?)
        format.html { redirect_to rounds_path(:simulation_id=>Round.find(@round_expenses[0].round_id).simulation_id) }
        format.html { redirect_to @round_expense, notice: 'Round expense was successfully created.' }
        format.json { render json: @round_expense, status: :created, location: @round_expense }
      else
        format.html { render action: "new" }
        format.json { render json: @round_expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /round_expenses/1
  # PUT /round_expenses/1.json
  def update
    @round_expense = RoundExpense.find(params[:id])

    respond_to do |format|
      if @round_expense.update_attributes(params[:round_expense])
        format.html { redirect_to @round_expense, notice: 'Round expense was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @round_expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /round_expenses/1
  # DELETE /round_expenses/1.json
  def destroy
    @round_expense = RoundExpense.find(params[:id])
    @round_expense.destroy

    respond_to do |format|
      format.html { redirect_to round_expenses_url }
      format.json { head :ok }
    end
  end
end

app/views/round_expenses/_form.html.erb
<%= form_for(@round_expense) do |f| %>
  <% if @round_expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round_expense.errors.count, "error") %> prohibited this round_expense from being saved:</h2>

      <ul>
      <% @round_expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :round_id %>
    <div class="input">

    <%= f.number_field :round_id %>
      </div>
  </div>


  <div class="clearfix">
    <%= f.label :expense_id %>
    <div class="input">
    <%= f.number_field :expense_id %>
  </div>
  </div>

  <div class="clearfix">
    <%= f.label :summary %>
    <div class="input">
    <%= f.text_area :summary %>
  </div>
  </div>

  <div class="row">
    <div class="span1 offset3">
    <%= f.submit "Submit",:class=>"primary btn" %>
      </div>
  </div>
<% end %>

app/views/round_expenses/edit.html.erb
<h1>Editing round_expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @round_expense %> |
<%= link_to 'Back', round_expenses_path %>

app/views/round_expenses/index.html.erb
<h1>Listing round_expenses</h1>

<table>
  <tr>
    <th>Round</th>
    <th>Expense</th>
    <th>Summary</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @round_expenses.each do |round_expense| %>
  <tr>
    <td><%= round_expense.round_id %></td>
    <td><%= round_expense.expense_id %></td>
    <td><%= round_expense.summary %></td>
    <td><%= link_to 'Show', round_expense %></td>
    <td><%= link_to 'Edit', edit_round_expense_path(round_expense) %></td>
    <td><%= link_to 'Destroy', round_expense, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Round expense', new_round_expense_path %>

app/views/round_expenses/new.html.erb
<script type="text/javascript">

    $(function() {
        $("#tabs_<%=@round.id %> li:first").addClass("active");
        $("#tab-content_<%=@round.id %> div:first").addClass("active");
    });
</script>

<!--The code to add new expense for that round-->

<h2>Expenses</h2>


<% @set_of_round_expenses[@round.id].each_with_index do |round_expense, index| %>
    <%= fields_for "set_of_round_expenses[#{@round.id}][#{index}]", round_expense do |f| %>



        <%= f.hidden_field :round_id, :value=>@round.id %>
        <%= f.hidden_field :expense_id, :value=>@expenses[index].id %>
        <script type="text/javascript">
            $(function() {

                <%  if !@expenses[index].summary.blank? %>

                var s ='"'+ "<%=@expenses[index].summary%>"+'"';
                <% end %>

                $("#" + "<%=ExpenseType.find(@expenses[index].expense_type_id).name+"_"+@round.id.to_s %>").append('<div class="tab-pane clearfix" id="<%=@round.id %>"><div><b> <%=@expenses[index].name %></b> </div>' + s + ' <br> <%= f.check_box :expense_id,{},@expenses[index].id,0%> </div><br>');

            });

        </script>

    <% end %>

<% end %>


<ul class="tabs" id="tabs_<%= @round.id %>">
  <% @expense_types.each_with_index do |expense_type, index| %>
      <li><a href="#<%= expense_type.name+"_"+@round.id.to_s %>"><%= expense_type.name %></a></li>
  <% end %>
</ul>
<div class="tab-content" id="tab-content_<%= @round.id %>">

  <% @expense_types.each_with_index do |expense_type, index| %>

      <div class="tab-pane" id="<%= expense_type.name+"_"+@round.id.to_s %>">


      </div>
  <% end %>

</div>



<script type="text/javascript">
    $(function() {
        $(".tabs").tabs();
    });

</script>

app/views/round_expenses/show.html.erb
<p>
  <b>Round:</b>
  <%= @round_expense.round_id %>
</p>

<p>
  <b>Expense:</b>
  <%= @round_expense.expense_id %>
</p>

<p>
  <b>Summary:</b>
  <%= @round_expense.summary %>
</p>


<%= link_to 'Edit', edit_round_expense_path(@round_expense) %> |
<%= link_to 'Back', round_expenses_path %>