config/routes.rb
Layouter::Application.routes.draw do
  resources :environmental_decision_parameters

  resources :market_demographics

  resources :mentality_values

  resources :mentality_rankings

  resources :mentalities

  resources :mentality_parameters

  resources :factory_vendors

  resources :plugin_samples

  resources :jquery_themes

  resources :font_themes

  resources :icon_themes

  resources :temps

  resources :pages

  resources :page_layouts

  resources :layout_themes

  resources :color_themes

  # get "welcome/index"
  match '/jquery_sample' => 'color_themes#jquery_sample'
  match '/icon_sample' => 'color_themes#icon_sample'
  match '/check_theme' => 'page_layouts#check_theme'


  resources :brands

  resources :player_round_factories

  resources :round_media_plans

  resources :player_round_loans

  resources :player_round_investments

  resources :player_round_expenses

  resources :default_player_data

  resources :players

  resources :player_financials

  resources :imports

  resources :games

  resources :student_group_users

  resources :round_loans

  resources :loan_types

  resources :investment_types

  resources :round_expenses

  resources :employees

  resources :employee_categories

  resources :constants

  resources :round_investments

  resources :media_plan_details

  resources :media_plans

  resources :impacts

  resources :units

  resources :expense_types

  resources :hrincentives

  resources :simulation_decision_parameters

  resources :simulation_markets

  resources :simulation_factories

  resources :student_groups

  resources :facilitator_groups

  resources :product_parameters

  resources :raw_materials

  resources :products

  resources :mathematical_model_variable_values

  resources :available_decision_parameters

  resources :mathematical_model_constant_values

  resources :mathematical_model_variables

  resources :mathematical_model_constants

  resources :round_environmental_parameters

  resources :expense_options

  resources :expenses

  resources :case_studies

  resources :player_investments

  resources :investments

  resources :player_loans

  resources :loans

  resources :media

  resources :consumer_brand_selection_parameters

  resources :brand_selection_parameters

  resources :consumer_media_preferences

  resources :consumer_categories

  resources :consumers

  resources :vendors

  resources :dealer_categories

  resources :dealer_push_indices

  resources :dealers

  resources :market_consumer_categories

  resources :market_distances

  resources :factories

  resources :markets

  resources :rounds

  resources :simulations

  resources :mathematical_model_inputs

  resources :mathematical_models

  resources :decision_parameters

  resources :environmental_parameters

  resources :facilitators

  resources :clients

  devise_for :users do
    get '/users/sign_out'=>'devise/sessions#destroy'
  end

  root :to=>'welcome#landing_page'

  match 'home_page'=>'welcome#home_page'

  match "define_constant_value"=>'decision_parameters#define_constant_value'
  match "set_constant_value"=>'decision_parameters#set_constant_value'
  match "define_variable_values"=>'decision_parameters#define_variable_values'
  match "set_variable_values"=>'decision_parameters#set_variable_values'
  match 'details'=>'decision_parameters#view_details'
  match 'view_parameters'=>'products#view_parameters'
  match 'view_expenses'=>'expenses#view_expenses'
  match 'view_distances'=>'markets#view_distances'
  match 'initiate_game'=>'games#initiate_game'
  match "get_student_group"=>'simulations#get_student_group'
  match "set_student_group"=>'simulations#set_student_group'
  match 'initiate_simulation'=>'simulations#initiate_simulation'
  match "register_as_expense"=>'media_plans#register_as_expense'
  match 'landing_page'=>'welcome#landing_page'
  match 'populate_rate_of_interest'=>'rounds#populate_rate_of_interest'
  match 'populate_depreciation'=>'rounds#populate_depreciation'
  match 'set_rate_of_interest'=>'rounds#set_rate_of_interest'
  match 'set_depreciation'=>'rounds#set_depreciation'
  match 'finalize_media_plan'=>'media_plans#finalize_media_plan'
  match 'select_initiate_simulation'=>'simulations#select_initiate_simulation'
  match 'view_tabular_market_distance'=>'market_distances#view_tabular_distances'
  match 'initiate_round_calculation'=>'simulations#initiate_round_calculation'
  match 'view_map'=>'markets#view_maps'
  match 'set_location'=>'markets#set_location'
  match 'update_market_distance'=>'market_distances#update_distances'
  match 'participation_management'=>'welcome#participation_management'
  match 'set_participation'=>'welcome#set_participation'
  match 'remove_student/:student_group_user_id', :to=>'welcome#remove_student'
  match 'set_simulation'=>'welcome#set_simulation'
  match 'remove_student_from_list/:user_id'=>'welcome#remove_student_from_list'
  match 'remove_media_plan_detail'=>'media_plans#remove_media_plan_detail'
  match 'register_as_expense'=>'media_plans#register_as_expense'


end

app/models/brand_selection_parameter.rb
class BrandSelectionParameter < ActiveRecord::Base
end

app/controllers/brand_selection_parameters_controller.rb
class BrandSelectionParametersController < ApplicationController
  # GET /brand_selection_parameters
  # GET /brand_selection_parameters.json
  def index
    @brand_selection_parameters = BrandSelectionParameter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brand_selection_parameters }
    end
  end

  # GET /brand_selection_parameters/1
  # GET /brand_selection_parameters/1.json
  def show
    @brand_selection_parameter = BrandSelectionParameter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand_selection_parameter }
    end
  end

  # GET /brand_selection_parameters/new
  # GET /brand_selection_parameters/new.json
  def new
    @brand_selection_parameter = BrandSelectionParameter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand_selection_parameter }
    end
  end

  # GET /brand_selection_parameters/1/edit
  def edit
    @brand_selection_parameter = BrandSelectionParameter.find(params[:id])
  end

  # POST /brand_selection_parameters
  # POST /brand_selection_parameters.json
  def create
    @brand_selection_parameter = BrandSelectionParameter.new(params[:brand_selection_parameter])

    respond_to do |format|
      if @brand_selection_parameter.save
        format.html { redirect_to @brand_selection_parameter, notice: 'Brand selection parameter was successfully created.' }
        format.json { render json: @brand_selection_parameter, status: :created, location: @brand_selection_parameter }
      else
        format.html { render action: "new" }
        format.json { render json: @brand_selection_parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brand_selection_parameters/1
  # PUT /brand_selection_parameters/1.json
  def update
    @brand_selection_parameter = BrandSelectionParameter.find(params[:id])

    respond_to do |format|
      if @brand_selection_parameter.update_attributes(params[:brand_selection_parameter])
        format.html { redirect_to @brand_selection_parameter, notice: 'Brand selection parameter was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand_selection_parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brand_selection_parameters/1
  # DELETE /brand_selection_parameters/1.json
  def destroy
    @brand_selection_parameter = BrandSelectionParameter.find(params[:id])
    @brand_selection_parameter.destroy

    respond_to do |format|
      format.html { redirect_to brand_selection_parameters_url }
      format.json { head :ok }
    end
  end
end

app/views/brand_selection_parameters/_form.html.erb
<%= form_for(@brand_selection_parameter) do |f| %>
  <% if @brand_selection_parameter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand_selection_parameter.errors.count, "error") %> prohibited this brand_selection_parameter from being saved:</h2>

      <ul>
      <% @brand_selection_parameter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brand_selection_parameters/edit.html.erb
<%= content_for :main_content do %>
<h1>Editing brand_selection_parameter</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand_selection_parameter %> |
<%= link_to 'Back', brand_selection_parameters_path %>

<% end %>

app/views/brand_selection_parameters/index.html.erb
<%= content_for :main_content do %>
<h1>Listing brand_selection_parameters</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @brand_selection_parameters.each do |brand_selection_parameter| %>
  <tr>
    <td><%= brand_selection_parameter.name %></td>
    <td><%= link_to 'Show', brand_selection_parameter %></td>
    <td><%= link_to 'Edit', edit_brand_selection_parameter_path(brand_selection_parameter) %></td>
    <td><%= link_to 'Destroy', brand_selection_parameter, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brand selection parameter', new_brand_selection_parameter_path %>

<% end %>

app/views/brand_selection_parameters/new.html.erb
<%= content_for :main_content do %>
<h1>New brand_selection_parameter</h1>

<%= render 'form' %>

<%= link_to 'Back', brand_selection_parameters_path %>

<% end %>

app/views/brand_selection_parameters/show.html.erb
<%= content_for :main_content do %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @brand_selection_parameter.name %>
</p>


<%= link_to 'Edit', edit_brand_selection_parameter_path(@brand_selection_parameter) %> |
<%= link_to 'Back', brand_selection_parameters_path %>

<% end %>