config/routes.rb
Layouter::Application.routes.draw do
  resources :environmental_decision_parameters

  resources :market_demographics

  resources :mentality_values

  resources :mentality_rankings

  resources :mentalities

  resources :mentality_parameters

  resources :factory_vendors

  resources :plugin_samples

  resources :jquery_themes

  resources :font_themes

  resources :icon_themes

  resources :temps

  resources :pages

  resources :page_layouts

  resources :layout_themes

  resources :color_themes

  # get "welcome/index"
  match '/jquery_sample' => 'color_themes#jquery_sample'
  match '/icon_sample' => 'color_themes#icon_sample'
  match '/check_theme' => 'page_layouts#check_theme'


  resources :brands

  resources :player_round_factories

  resources :round_media_plans

  resources :player_round_loans

  resources :player_round_investments

  resources :player_round_expenses

  resources :default_player_data

  resources :players

  resources :player_financials

  resources :imports

  resources :games

  resources :student_group_users

  resources :round_loans

  resources :loan_types

  resources :investment_types

  resources :round_expenses

  resources :employees

  resources :employee_categories

  resources :constants

  resources :round_investments

  resources :media_plan_details

  resources :media_plans

  resources :impacts

  resources :units

  resources :expense_types

  resources :hrincentives

  resources :simulation_decision_parameters

  resources :simulation_markets

  resources :simulation_factories

  resources :student_groups

  resources :facilitator_groups

  resources :product_parameters

  resources :raw_materials

  resources :products

  resources :mathematical_model_variable_values

  resources :available_decision_parameters

  resources :mathematical_model_constant_values

  resources :mathematical_model_variables

  resources :mathematical_model_constants

  resources :round_environmental_parameters

  resources :expense_options

  resources :expenses

  resources :case_studies

  resources :player_investments

  resources :investments

  resources :player_loans

  resources :loans

  resources :media

  resources :consumer_brand_selection_parameters

  resources :brand_selection_parameters

  resources :consumer_media_preferences

  resources :consumer_categories

  resources :consumers

  resources :vendors

  resources :dealer_categories

  resources :dealer_push_indices

  resources :dealers

  resources :market_consumer_categories

  resources :market_distances

  resources :factories

  resources :markets

  resources :rounds

  resources :simulations

  resources :mathematical_model_inputs

  resources :mathematical_models

  resources :decision_parameters

  resources :environmental_parameters

  resources :facilitators

  resources :clients

  devise_for :users do
    get '/users/sign_out'=>'devise/sessions#destroy'
  end

  root :to=>'welcome#landing_page'

  match 'home_page'=>'welcome#home_page'

  match "define_constant_value"=>'decision_parameters#define_constant_value'
  match "set_constant_value"=>'decision_parameters#set_constant_value'
  match "define_variable_values"=>'decision_parameters#define_variable_values'
  match "set_variable_values"=>'decision_parameters#set_variable_values'
  match 'details'=>'decision_parameters#view_details'
  match 'view_parameters'=>'products#view_parameters'
  match 'view_expenses'=>'expenses#view_expenses'
  match 'view_distances'=>'markets#view_distances'
  match 'initiate_game'=>'games#initiate_game'
  match "get_student_group"=>'simulations#get_student_group'
  match "set_student_group"=>'simulations#set_student_group'
  match 'initiate_simulation'=>'simulations#initiate_simulation'
  match "register_as_expense"=>'media_plans#register_as_expense'
  match 'landing_page'=>'welcome#landing_page'
  match 'populate_rate_of_interest'=>'rounds#populate_rate_of_interest'
  match 'populate_depreciation'=>'rounds#populate_depreciation'
  match 'set_rate_of_interest'=>'rounds#set_rate_of_interest'
  match 'set_depreciation'=>'rounds#set_depreciation'
  match 'finalize_media_plan'=>'media_plans#finalize_media_plan'
  match 'select_initiate_simulation'=>'simulations#select_initiate_simulation'
  match 'view_tabular_market_distance'=>'market_distances#view_tabular_distances'
  match 'initiate_round_calculation'=>'simulations#initiate_round_calculation'
  match 'view_map'=>'markets#view_maps'
  match 'set_location'=>'markets#set_location'
  match 'update_market_distance'=>'market_distances#update_distances'
  match 'participation_management'=>'welcome#participation_management'
  match 'set_participation'=>'welcome#set_participation'
  match 'remove_student/:student_group_user_id', :to=>'welcome#remove_student'
  match 'set_simulation'=>'welcome#set_simulation'
  match 'remove_student_from_list/:user_id'=>'welcome#remove_student_from_list'
  match 'remove_media_plan_detail'=>'media_plans#remove_media_plan_detail'
  match 'register_as_expense'=>'media_plans#register_as_expense'


end

app/models/round_environmental_parameter.rb
class RoundEnvironmentalParameter < ActiveRecord::Base
  belongs_to :round
end

app/controllers/round_environmental_parameters_controller.rb
class RoundEnvironmentalParametersController < ApplicationController
  # GET /round_environmental_parameters
  # GET /round_environmental_parameters.json
  def index
    @round_environmental_parameters = RoundEnvironmentalParameter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @round_environmental_parameters }
    end
  end

  # GET /round_environmental_parameters/1
  # GET /round_environmental_parameters/1.json
  def show
    @round_environmental_parameter = RoundEnvironmentalParameter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @round_environmental_parameter }
    end
  end

  # GET /round_environmental_parameters/new
  # GET /round_environmental_parameters/new.json
  def new
    @round=Round.find(params[:round_id])
    @round_environmental_parameter = RoundEnvironmentalParameter.new

    @included_parameters=@round.round_environmental_parameters
    @included_parameters_ids=Array.new
    @included_parameters.each do |parameter|
      @included_parameters_ids << parameter.environmental_parameter_id
    end

    @environmental_parameter_list=EnvironmentalParameter.all.collect{|parameter| if @included_parameters_ids.include?(parameter.id)==false then [parameter.name,parameter.id] end}.compact


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @round_environmental_parameter }
    end
  end

  # GET /round_environmental_parameters/1/edit
  def edit
    @round_environmental_parameter = RoundEnvironmentalParameter.find(params[:id])
  end

  # POST /round_environmental_parameters
  # POST /round_environmental_parameters.json
  def create
    @round_environmental_parameter = RoundEnvironmentalParameter.new(params[:round_environmental_parameter])

    respond_to do |format|
      if @round_environmental_parameter.save
        format.html {redirect_to new_round_environmental_parameter_path(:round_id=>@round_environmental_parameter.round_id)}
       # format.html { redirect_to @round_environmental_parameter, notice: 'Round environmental parameter was successfully created.' }
        format.json { render json: @round_environmental_parameter, status: :created, location: @round_environmental_parameter }
      else
        format.html { render action: "new" }
        format.json { render json: @round_environmental_parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /round_environmental_parameters/1
  # PUT /round_environmental_parameters/1.json
  def update
    @round_environmental_parameter = RoundEnvironmentalParameter.find(params[:id])

    respond_to do |format|
      if @round_environmental_parameter.update_attributes(params[:round_environmental_parameter])
        format.html { redirect_to @round_environmental_parameter, notice: 'Round environmental parameter was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @round_environmental_parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /round_environmental_parameters/1
  # DELETE /round_environmental_parameters/1.json
  def destroy
    @round_environmental_parameter = RoundEnvironmentalParameter.find(params[:id])
    @round_environmental_parameter.destroy

    respond_to do |format|
      format.html { redirect_to round_environmental_parameters_url }
      format.json { head :ok }
    end
  end
end

app/views/round_environmental_parameters/_form.html.erb
<%= form_for(@round_environmental_parameter) do |f| %>
  <% if @round_environmental_parameter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round_environmental_parameter.errors.count, "error") %> prohibited this round_environmental_parameter from being saved:</h2>

      <ul>
      <% @round_environmental_parameter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :round %><br />
    <%= f.number_field :round %>
  </div>
  <div class="field">
    <%= f.label :environmental_parameter_id %><br />
    <%= f.number_field :environmental_parameter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/round_environmental_parameters/edit.html.erb
<%= content_for :main_content do %>
<h1>Editing round_environmental_parameter</h1>

<%= render 'form' %>

<%= link_to 'Show', @round_environmental_parameter %> |
<%= link_to 'Back', round_environmental_parameters_path %>
<% end %>

app/views/round_environmental_parameters/index.html.erb
<%= content_for :main_content do %>
<h1>Listing round_environmental_parameters</h1>

<table>
  <tr>
    <th>Round</th>
    <th>Environmental parameter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @round_environmental_parameters.each do |round_environmental_parameter| %>
  <tr>
    <td><%= round_environmental_parameter.round %></td>
    <td><%= round_environmental_parameter.environmental_parameter_id %></td>
    <td><%= link_to 'Show', round_environmental_parameter %></td>
    <td><%= link_to 'Edit', edit_round_environmental_parameter_path(round_environmental_parameter) %></td>
    <td><%= link_to 'Destroy', round_environmental_parameter, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Round environmental parameter', new_round_environmental_parameter_path %>
<% end%>

app/views/round_environmental_parameters/new.html.erb
<%= content_for :main_content do %>
<div style="width: 50%">
  <h1>New round_environmental_parameter</h1>



<%= form_for(@round_environmental_parameter) do |f| %>
  <% if @round_environmental_parameter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round_environmental_parameter.errors.count, "error") %> prohibited this round_environmental_parameter from being saved:</h2>

      <ul>
      <% @round_environmental_parameter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.hidden_field :round_id,:value=>@round.id %>

  <div class="field">
    <%= f.label :environmental_parameter_id %><br />
    <%= f.select :environmental_parameter_id,@environmental_parameter_list %>
  </div>

<div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

















</div>
<div style="margin-left: 50%">

  <ul>
    <% @included_parameters.each do |parameter| %>
    <li><%= EnvironmentalParameter.find(parameter.environmental_parameter_id).name %></li>
    <% end %>
    </ul>


  <%= link_to 'Done', rounds_path(:simulation_id=>@round.simulation_id) %>
</div><% end %>

app/views/round_environmental_parameters/show.html.erb
<%= content_for :main_content do %>
<p id="notice"><%= notice %></p>

<p>
  <b>Round:</b>
  <%= @round_environmental_parameter.round %>
</p>

<p>
  <b>Environmental parameter:</b>
  <%= @round_environmental_parameter.environmental_parameter_id %>
</p>


<%= link_to 'Edit', edit_round_environmental_parameter_path(@round_environmental_parameter) %> |
<%= link_to 'Back', round_environmental_parameters_path %>
<% end %>